# Generated by Django 4.2.22 on 2025-06-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timetable_remove_timetableentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='owner',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='timetable',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='app.timetable'),
            preserve_default=False,
        ),
    ]
