# Generated by Django 4.2.22 on 2025-06-17 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_remove_bookingrequest_owner_bookingrequest_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
