# Generated by Django 4.2.22 on 2025-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingrequest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='guest_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='guest_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
